#parameters:
#    env(ELASTICSEARCH_HOST): '172.21.0.2:9200'

api_platform:
    defaults:
        pagination_enabled: true
        pagination_items_per_page: 10
    collection:
        pagination:
            page_parameter_name: _page
#            items_per_page_parameter_name: itemsPerPage # Default value
    mapping:
        paths: ['%kernel.project_dir%/app/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
#    elasticsearch:
#        # To enable or disable Elasticsearch support.
#        enabled: true
#
#        # The hosts to the Elasticsearch nodes.
#        hosts: ['%env(ELASTICSEARCH_HOST)%']
#
#        # The mapping between resource classes and indexes.
#        mapping: [ ]